// generated by "sampctl package generate"

#define FOREACH_I_PlayerPlayersStream 1
#define FOREACH_I_VehiclePlayersStream 1
#include "foreach"
#include "gtolib.inc"

main() {
	// write tests for libraries here and run "sampctl package run"
}
